### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by aenesgur** [thrkrdk/graphql#1]
Selam
Subfield'lar için pagination nasıl yapılır? 
`allUser{
id
role(take:3) {
name
}
} `
Örneğin yukarıdaki sorgudaki gibi tüm rolleri donmektense sadece 3 tane dönmek istiyorum
Schemada bunu nasıl tanımlayabilirim, syntax hatası alıyorum bunu yaparken

**Comment by krdk01** [comment]
@aenesgur  Selam.
Soruyu tam anlayamadım. örnek bir data set , sorgu veya kod blogu gönderebilirsen, bildiğim bir konuysa yardımcı olmaya çalışayım.

**Comment by aenesgur** [comment]
@thrkrdk selam
Sizin uygulamanızdaki senaryo üzerinden örnek vermek gerekirse "allUsers" query'siyle tüm kullanıcıları dönerken aynı zamanda kullanıcılara ait olan tüm rolleride dönmekteyiz. Örnek query:
```
allUser{
   id
   name
   roles2{
     id
     name
   }
}
```
 
Örneğin ben bu rollerden sadece 1 tanesini dönmek istiyorum yani paging, filtering on subfield yapmak  istiyorum. Oluşturmak istediğim örnek query:
 
```
allUser{
   id
   name
   roles2(take:2){
     id
     name
   }
}
```

Sizin uygulamanızda schema tarafında User type'ını "roles2" field'ına "take" parametresi geçerek aşağıdaki gibi güncelledim:
```
type User {
    id: ID!
    firstName: String
    lastName: String
    email: String
    roles: [Role!]
    roles2(take: Int): [Role!]
    birthDate: Date
}
```

ve User Resolver'ı da aşağıdaki gibi "roles2" methoduna ekstra olarak "Integer take" parametresi geçerek güncelledim:
```
@Component
@RequiredArgsConstructor
@Slf4j
public class UserResolver implements GraphQLResolver<User> {

    private final IRoleService roleService;

    public List<Role> roles(User user) {
        return roleService.roleByUserId(user.getId());
    }

    public String firstName(User user) {
        log.info("Kişinin adının sonuna rasgele numara eklendi");
        return user.getFirstName().concat(String.valueOf((new Random()).nextInt(10)));
    }

    public CompletableFuture<List<Role>> roles2(User user, Integer take, DataFetchingEnvironment dfe) {
        final DataLoader<Long, List<Role>> dataloader = dfe.getDataLoaderRegistry().getDataLoader("userRoleDataLoader");
        System.out.println(take);
        return dataloader.load(user.getId(), user);
    }
}
```

Bu şekilde güncelleyip istediğim sorguyu attığımda "take" değerini yakalayabiliyorum, burada isteğim dataloader ile db'den "take" ile yolladığım değer kadar kayıt döndürmek istiyorum, bunu nasıl yapabilirim? 
JPA'da çalışmasını istediğim örnek sql: `select * from role limit :take;`

Take değerini resolverdaki "roles" methoduna yollayıp `roleService.roleByUserId(user.getId(), take); ` roleService ile jpa da native query ile çalıştırabilirim fakat burada n+1 problemine takılacağım. Ben bunu "roles2" 'de dataloader ile nasıl yapabilirim?

Cevabınızı beklemekteyim :) 
Sevgiler

**Comment by krdk01** [comment]
Selam
parametre eklemene gerek yok aslında DataFetchingEnvironment  dan method'a servis çağrısı yaptığın paramterleri alabilirsin.
![image](https://user-images.githubusercontent.com/7022571/112595107-01c6d080-8e1b-11eb-9b46-1aad66ff19c7.png)
aldığın parametre ile repository de findByNTop  methodu yazarak alabilirisin diye tahmin ediyorum

**Comment by aenesgur** [comment]
@thrkrdk selam,
DataFetchingEnvironment'dan parametreyi yakaladım, fakat bu parametreyi dataloader'a nasıl göndereceğim n+1'e takılmamak için. Direkt olarak repository'e bağlanıp limitli çekersem allUsers query'sinde her kullanıcı için teker teker db'ye gideceğim. 
Integer take'i resolver'dan göndermek için göndermek için Dataloader'ı nasıl güncellemeliyim?
```
private DataLoaderRegistry buildDataLoaderRegistry() {
        DataLoaderRegistry dataLoaderRegistry = new DataLoaderRegistry();

        MappedBatchLoader<Long, List<Role>> userMappedBatchLoader =
                userIds -> CompletableFuture.supplyAsync(() -> {
                    List<Role> customers = roleService.findByUser_IdIn(userIds);
                    return customers.stream().collect(Collectors.groupingBy(roles -> roles.getUser().getId()));
                }, new SyncTaskExecutor());


        dataLoaderRegistry.register("userRoleDataLoader",
                DataLoader.newMappedDataLoader(userMappedBatchLoader));
        return dataLoaderRegistry;
    }
```


```
public CompletableFuture<List<Role>> roles2(User user, DataFetchingEnvironment dfe) {
        final DataLoader<Long, List<Role>> dataloader = dfe.getDataLoaderRegistry().getDataLoader("userRoleDataLoader");
       
        return dataloader.load(user.getId(), user);
    }
```

**Comment by krdk01** [comment]
Enes Selam
N+1 'de  limit koyarsan istediğin sonucu alamazsın.
Select * from role where user_id in (1,2,3) order by id limit 2 dersen
çıktının sonucu 1 nolu user'a ait olan iki tane rolü alırsın diğer kullanıcıların rolünü alamazsın

http://localhost:3002/api/graphiql den aşağıdaki sorguyu çalıştırdım. sonucu resimde görebilirsin
`query GET_ALLUSER {
    allUser {
        id
        firstName
        roles2{id, name}
    }
}`
![image](https://user-images.githubusercontent.com/7022571/112625657-4add4b80-8e40-11eb-92a2-1271274c8015.png)

Örnek kodu da ekliyorum.  RoleService.java da 35.nci satırda debug koyarak kendin gözlemleyebilirsin
[graphql-main.zip](https://github.com/thrkrdk/graphql/files/6211472/graphql-main.zip)

Ama tek bir kullanııya ait rollerde limit işleminde n+1 doğru çalışacaktır. Benim örneğimide tüm kullanılara ait roller getiriliyor
umarım doğru anlamışımdır.
Kolay gelsin

**Comment by aenesgur** [comment]
@thrkrdk selam

teşekkür ederim şimdi kafamda daha çok şekillendi 

Tekrar elinize sağlık :)
 Kolay gelsin

**Comment by krdk01** [comment]
Yardımcı olabildiysem sevindim.
Kolay Gelsin
